/**
 * Enterprise PDF Invoice Engine
 */
import { Storage } from './core.js';

export const InvoiceEngine = {
    /**
     * Generate Student PDF Invoice
     * @param {Object} data { studentName, items: [{desc, price}], total, paid, date }
     */
    async generateInvoice(data) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF({
            orientation: 'p',
            unit: 'mm',
            format: 'a4'
        });

        // Load Arabic font if possible, or use basic layout
        // Note: Basic jsPDF doesn't support RTL/Arabic perfectly without plugins
        // Simulating a professional layout using lines and standard boxes

        const center = doc.internal.pageSize.getWidth() / 2;

        // Header
        doc.setFontSize(22);
        doc.text("EduMaster Pro", center, 20, { align: 'center' });
        doc.setFontSize(10);
        doc.text("Official Invoice / فاتورة ضريبية مبسطة", center, 28, { align: 'center' });

        // Horizontal Line
        doc.setLineWidth(0.5);
        doc.line(10, 35, 200, 35);

        // Bill To
        doc.setFontSize(12);
        doc.text(`Invoice No: INV-${Date.now().toString().slice(-6)}`, 10, 45);
        doc.text(`Date: ${data.date || new Date().toLocaleDateString()}`, 10, 52);
        doc.text(`Student: ${data.studentName}`, 10, 59);

        // Table Header
        doc.setFillColor(240, 240, 240);
        doc.rect(10, 70, 190, 8, 'F');
        doc.text("Description / البيان", 15, 76);
        doc.text("Amount / المبلغ", 170, 76);

        // Table Content
        let y = 85;
        data.items.forEach(item => {
            doc.text(item.desc, 15, y);
            doc.text(item.price.toLocaleString() + " EGP", 170, y);
            y += 8;
        });

        // Summary
        doc.line(10, y, 200, y);
        y += 10;
        doc.setFontSize(14);
        doc.text(`Total: ${data.total.toLocaleString()} EGP`, 150, y);
        y += 8;
        doc.text(`Paid: ${data.paid.toLocaleString()} EGP`, 150, y);
        y += 8;
        doc.setFontSize(16);
        doc.setTextColor(16, 185, 129); // Accent Green
        doc.text(`Balance: ${(data.total - data.paid).toLocaleString()} EGP`, 150, y);

        // Footer
        doc.setTextColor(150);
        doc.setFontSize(9);
        doc.text("Generated by EduMaster Pro ERP System", center, 280, { align: 'center' });

        // Save
        doc.save(`Invoice_${data.studentName}_${Date.now()}.pdf`);
    }
};
